spring:
 profiles: 
  active: 
   - dev
   
---
spring:
  profiles: dev
  application:
    name: springcloudConfigServer-dev
---   
spring:
  profiles: test
  application:
    name: springcloudConfigServer-tea