spring:
 profiles: 
  active: 
   - dev
   
---
spring:
  profiles: dev
  application:
    name: springcloudConfigCilent-dev
server:
  port: 3355

eureka:
  instance:
    hostname: eureka7001
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://eureka7003:7003/eureka/    #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。    
---   
spring:
  profiles: test
  application:
    name: springcloudConfigCilent-test
server:
  port: 3366

eureka:
  instance:
    hostname: eureka7001
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://eureka7004:7004/eureka/    #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。    